import: minimind.yaml

override:
  model.tokenizer: LiquidAI/LFM2-350M
  pretrain.batch_size: 16
  pretrain.optimizer:
    name: lion
    learning_rate: 1e-4
    weight_decay: 0.01
  sft.batch_size: 16
  sft.optimizer:
    name: lion
    learning_rate: 1e-4
    weight_decay: 0.01
  dpo.batch_size: 16
  dpo.optimizer:
    name: lion
    learning_rate: 1e-4
    weight_decay: 0.01
