import: default.yaml

model:
  generation:
    max_length: 2048

train:
  pretrain:
    dataset: datasets/fineweb-10bt

  sft:
    dataset:
      # - datasets/openhermes-2.5
      - datasets/magpie-pro-300k-filtered
      - datasets/ultrachat_200k
      - datasets/identity/pico-sft

  dpo:
    dataset:
      - datasets/magpielm-dpo-data-v0.1
      - datasets/identity/pico-dpo
