# Use datasets from Minimind2: https://github.com/jingyaogong/minimind/blob/master/README_en.md
import: default.yaml

model:
  rope_scaling:
    original_max_position_embeddings: 512

train:
  pretrain:
    dataset: datasets/minimind/pretrain_hq.jsonl
    max_length: 512
    batch_size: 16
    warmup_steps: 100
    accumulation_steps: 4
