import: default.yaml

override:
  pretrain.dataset:
    name: vblagoje/cc_news
    ratio: 0.5
  pretrain.optimizer:
    name: adamw
    learning_rate: 5e-4
  pretrain.context_length: 512
  pretrain.batch_size: 16
  sft: null
  dpo: null
