import: default.yaml

model:
  hidden_size: 512
  num_hidden_layers: 12
  num_attention_heads: 8
  num_kv_attention_heads: 2
  feed_forward_size: 1700

train:
  pretrain:
    dataset:
      path: datasets/fineweb-10bt
      ratio: 0.01
