model:
  name: pixie
  tokenizer: microsoft/phi-4
  hidden_size: 512
  num_hidden_layers: 8
  num_attention_heads: 8
  num_kv_attention_heads: 2
  feed_forward_size: 1408

pretrain:
  context_length: 1024
  dataset:
    path: datasets/pile
    limit: 2000000
  epochs: 1
  batch_size: 4
  learning_rate: 5e-4
  grad_clip: 1.0
  warmup_steps: 400
